on:
  workflow_dispatch:
  
name: Deploy Bicep Demo

permissions:
      id-token: write
      contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v5
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file
    - name: Deploy the bicep file
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: RG_PolicyTest
        template: ./MC/storageaccount.bicep
        parameters: ./MC/storageaccount-Test.parameters.json
